dist: trusty
sudo: false
language: node_js

matrix:
  include:
    - node_js: "node"
      env: NODE_VERSION=node
    - node_js: "10"
      env: NODE_VERSION=10
    - node_js: "9"
      env: NODE_VERSION=9
    - node_js: "8"
      env: NODE_VERSION=8

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

services:
  - mongodb

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm test -- test/unit/
  - npm test -- test/integration/
  - npm test -- test/e2e/